name: services
version: 1.0.0
description: Services package
publish_to: "none"

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  chopper: ^4.0.1
  json_annotation: ^4.1.0
  get_it: ^7.2.0

dev_dependencies:
  build_runner: ^2.1.4
  chopper_generator: ^4.0.2
  json_serializable: ^5.0.2
  swagger_dart_code_generator: ^2.2.1
